name: Trigger Dependabot on Push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Dependabot
        uses: peter-evans/dependabot-auto-merge@v3
        with:
          command: version
