name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag for the release (e.g., v1.0.0)'
        required: true
      release_title:
        description: 'Release title'
        required: true
      release_description:
        description: 'Release description'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache Gradle files
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK to release
        id: upload-release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version_tag }}
          name: ${{ github.event.inputs.release_title }}
          body: ${{ github.event.inputs.release_description }}
          draft: false
          prerelease: false
          files: |
            app/build/outputs/apk/release/app-release.apk

      - name: Show release URL
        run:
          echo 'Release created at: ${{ steps.upload-release.outputs.url }}'
