name: Build and Release APK

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for the release'
        required: true
        default: 'v1.0.0'
      release_title:
        description: 'Release title'
        required: true
        default: 'Initial Release'
      release_description:
        description: 'Release description'
        required: true
        default: 'Description of the release'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Gradle (Release)
        run: ./gradlew assembleRelease

      - name: List APK Directory (Debugging Step)
        run: ls -R app/release/

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/release/app-release.apk

  create_release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag_name }}
          release_name: ${{ github.event.inputs.release_title }}
          body: ${{ github.event.inputs.release_description }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

